Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blet?serverTimezone=UTC
    username: root
    password: fhald0115@

  jpa:
    hibernate: # hibernate ?? ??
        # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
        # if exists drop table ??? ?? ?????? ?? ??.
      ddl-auto: create-drop
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true